# See application.yml (via DATABASE_URL)
#
# WARNING - DO NOT STORE DATABASE CREDS IN THIS FILE - Use application.yml instead. This file needs to exist for default
#   capybara stuff to work but needs no content.
#
development:
  adapter: postgresql
  encoding: unicode
  pool: 2
  database: octoreso_dev
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  pool: 2
  database: octoreso_test
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
