# See application.yml (via DATABASE_URL)
#
# WARNING - DO NOT STORE DATABASE CREDS IN THIS FILE - Use application.yml instead. This file needs to exist for default
#   capybara stuff to work but needs no content.
#
development:
  adapter: postgresql
  encoding: unicode
  database: octoreso_dev
  pool: 2
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: octoreso_test
  pool: 2
  username: postgres
  password: postgres

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
