Ingress::Community.create!(name: 'greece/athens')
Ingress::Community.create!(name: 'south_africa/plumstead')
Ingress::Community.create!(name: 'switzerland/neuchâtel')
Ingress::Community.create!(name: 'uk/aylesbury')
Ingress::Community.create!(name: 'uk/oxford')
Ingress::Community.create!(name: 'uk/bath')
Ingress::Community.create!(name: 'uk/newcastle')
Ingress::Community.create!(name: 'us/or/portland')

Ingress::Community.create!(name: 'uk/durham')
Ingress::Community.create!(name: 'uk/leeds')
Ingress::Community.create!(name: 'uk/reading')
Ingress::Community.create!(name: 'uk/hastings')
Ingress::Community.create!(name: 'uk/st_albans')
Ingress::Community.create!(name: 'usa/pa/pittsburgh')
Ingress::Community.create!(name: 'slovakia/topolcany')
Ingress::Community.create!(name: 'poland/szczecin')
